package com.example.omgupsandroidapp.presentation.ui.theme

import androidx.compose.ui.graphics.Color


val primaryLightMediumContrast = Color(0xFF004862)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF387C9C)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF004960)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF357C9B)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF01466E)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF4679A3)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF8C0009)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFDA342E)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFF6FAFE)
val onBackgroundLightMediumContrast = Color(0xFF171C1F)
val surfaceLightMediumContrast = Color(0xFFF6FAFE)
val onSurfaceLightMediumContrast = Color(0xFF171C1F)
val surfaceVariantLightMediumContrast = Color(0xFFDCE3E9)
val onSurfaceVariantLightMediumContrast = Color(0xFF3D4449)
val outlineLightMediumContrast = Color(0xFF596065)
val outlineVariantLightMediumContrast = Color(0xFF747C81)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF2C3134)
val inverseOnSurfaceLightMediumContrast = Color(0xFFEDF1F5)
val inversePrimaryLightMediumContrast = Color(0xFF8ECFF3)

val primaryDarkMediumContrast = Color(0xFF93D3F7)
val onPrimaryDarkMediumContrast = Color(0xFF001924)
val primaryContainerDarkMediumContrast = Color(0xFF5798BA)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFF91D3F5)
val onSecondaryDarkMediumContrast = Color(0xFF001924)
val secondaryContainerDarkMediumContrast = Color(0xFF5599B9)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFF9ED0FE)
val onTertiaryDarkMediumContrast = Color(0xFF00182A)
val tertiaryContainerDarkMediumContrast = Color(0xFF6495C1)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFBAB1)
val onErrorDarkMediumContrast = Color(0xFF370001)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF0F1417)
val onBackgroundDarkMediumContrast = Color(0xFFDFE3E7)
val surfaceDarkMediumContrast = Color(0xFF0F1417)
val onSurfaceDarkMediumContrast = Color(0xFFF8FBFF)
val surfaceVariantDarkMediumContrast = Color(0xFF41484D)
val onSurfaceVariantDarkMediumContrast = Color(0xFFC5CCD1)
val outlineDarkMediumContrast = Color(0xFF9DA4A9)
val outlineVariantDarkMediumContrast = Color(0xFF7D8489)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFDFE3E7)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF262B2E)
val inversePrimaryDarkMediumContrast = Color(0xFF004E69)